// <auto-generated />
namespace PatientCardWebClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adedfieldStreetinclassPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adedfieldStreetinclassPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100455499_aded field Street in class Patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
